#ifndef __PIT_H__
#define __PIT_H__

#include "Types.h"

//매ㅡㅋ로
#define PIT_FREQUENCY	1193182
#define MSTOCOUNT(x)	(PIT_FREQUENCY * (x) / 1000)
#define USTOCOUNT(x)	(PIT_FREQUENCY * (x) / 1000000)

//I/O 포트
#define PIT_PORT_CONTROL	0X43
#define PIT_PORT_COUNTER0	0X40
#define PIT_PORT_COUNTER1	0X41
#define PIT_PORT_COUNTER2	0X42

//모드
#define PIT_CONTROL_COUNTER0	0X00
#define PIT_CONTROL_COUNTER1	0X40
#define PIT_CONTROL_COUNTER2	0X80
#define PIT_CONTROL_LSBMSBRW	0X30
#define PIT_CONTROL_LATCH	0X00
#define PIT_CONTROL_MODE0	0X00
#define PIT_CONTROL_MODE2	0X04

//Binary or BCD
#define PIT_CONTROL_BINARYCOUNTER	0X00
#define PIT_CONTROL_BCDCOUNTER	0X01


#define PIT_COUNTER0_ONCE	(PIT_CONTROL_COUNTER0 | PIT_CONTROL_LSBMSBRW | PIT_CONTROL_MODE0 | PIT_CONTROL_BINARYCOUNTER)

#define PIT_COUNTER0_PERIODIC	(PIT_CONTROL_COUNTER0 | PIT_CONTROL_LSBMSBRW | PIT_CONTROL_MODE2 | PIT_CONTROL_BINARYCOUNTER)

#define PIT_COUNTER0_LATCH	(PIT_CONTROL_COUNTER0 | PIT_CONTROL_LATCH)

//함수
void kInitializePIT(WORD wCount, BOOL bPeriodic);
WORD kReadCounter0(void);
void kWaitUsingDirectPIT(WORD wCount);


#endif // !__PIT_H__

